# -*- coding: utf-8 -*-
"""analises_espaciais_vetoriais.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ikHFxac6FdYc5URsQvwFCucEd0qH_Uk5
"""

!pip install geopandas shapely matplotlib

import geopandas as gpd
import matplotlib.pyplot as plt
from shapely.geometry import Point, Polygon

# Criar dados vetoriais
points = gpd.GeoDataFrame(
    {"name": ["A", "B", "C"]},
    geometry=[
        Point(0, 0),
        Point(2000, 2000),
        Point(4000, 0)
    ],
    crs="EPSG:3857"
)

polygon = gpd.GeoDataFrame(
    {"area": ["Study Area"]},
    geometry=[
        Polygon([
            (-1000, -1000),
            (5000, -1000),
            (5000, 3000),
            (-1000, 3000)
        ])
    ],
    crs="EPSG:3857"
)

#VIsualizar os dados
base = polygon.plot(color="lightgrey", edgecolor="black", figsize=(6, 6))
points.plot(ax=base, color="red")
plt.title("Points and Study area")
plt.show()

# Criar um buffer 1000 m ao redor dos pontos
buffer = points.copy()
buffer["geometry"] = buffer.geometry.buffer(1000)

base = polygon.plot(color="lightgrey", edgecolor="black", figsize=(6, 6))
buffer.plot(ax=base, color="blue", alpha=0.4)
points.plot(ax=base, color="red")
plt.title("Buffer analysis (1000m)")
plt.show()

# Interseção entre buffer e área de estudo
intersection = gpd.overlay(buffer, polygon, how="intersection")
intersection

# Associar pontos a poligonos
join = gpd.sjoin(points, polygon, how="left", predicate="within")
join