# -*- coding: utf-8 -*-
"""Automation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lEx5nciFLFTLKCYvTYJr8J3FHZiL-pNd
"""

!wget http://naturalearth.s3.amazonaws.com/110m_cultural/ne_110m_admin_0_countries.zip
!unzip ne_110m_admin_0_countries.zip

import geopandas as gpd
import matplotlib.pyplot as plt

def analyze_continent(shapefile, continent_name):
    # Ler o dado
    gdf = gpd.read_file(shapefile)

    # Reprojetar para metros
    gdf = gdf.to_crs(epsg=3857)

    # Filtrar continente
    continent = gdf[gdf["CONTINENT"] == continent_name]

    # Calcular área em km2
    continent["area_km2"] = continent.area / 1e6

    # Mostrar área total
    total_area = continent["area_km2"].sum()
    print(f"total area of {continent_name}: {total_area:.2f} km2")

    # Mostrar mapa
    continent.plot(figsize=(8, 8), edgecolor="black")
    plt.show()

    return continent

def analyze_continent(shapefile, continent_name):
    gdf = gpd.read_file(shapefile)
    gdf = gdf.to_crs(epsg=3857)

    continent = gdf[gdf["CONTINENT"] == continent_name]

    continent["area_km2"] = continent.area / 1e6

    total_area = continent["area_km2"].sum()
    print(f"Total area of {continent_name}: {total_area:.2f} km²")

    continent.plot(figsize=(8, 8), edgecolor="black")
    plt.title(continent_name)
    plt.show()

    return continent

south_america = analyze_continent(
    "ne_110m_admin_0_countries.shp",
    "South America"
)

africa = analyze_continent(
    "ne_110m_admin_0_countries.shp",
    "Africa"
)

north_america = analyze_continent(
    "ne_110m_admin_0_countries.shp",
    "North America"
)