# -*- coding: utf-8 -*-
"""BANFF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tllXcoY0QSWXjWAZ4OXpty_kvtP-KFXs
"""

pip install ridge_map

from ridge_map import RidgeMap
import matplotlib.pyplot as plt

# Definindo as coordenadas de acordo com bounding box para Banff
mt_banff_bbox = (-117.6793,51.339,-115.3415,52.3865)

rm = RidgeMap(mt_banff_bbox)

# Dados de elevação
values = rm.get_elevation_data(num_lines=250)

# Processando informações
values = rm.preprocess(values=values,
                       lake_flatness=.5,
                       water_ntile=0,
                       vertical_ratio=200)

# Montando o mapa
rm.plot_map(values=values,
            label='Mt. Banff',
            label_y=0.1,
            label_x=0.55,
            label_size=40,
            linewidth=1,
            line_color=plt.get_cmap('copper'),
            kind='elevation')

