# -*- coding: utf-8 -*-
"""Buffer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nKyB1rnrawgSgCoNqjQSsPYRjzGeyYDi
"""

!wget http://naciscdn.org/naturalearth/110m/cultural/ne_110m_admin_0_countries.zip
!unzip ne_110m_admin_0_countries.zip

import geopandas as gpd
import matplotlib.pyplot as plt

world = gpd.read_file("ne_110m_admin_0_countries.shp")
world = world.to_crs(epsg=3857)

brazil = world[world["NAME"] == "Brazil"]

brazil.plot(color="lightgreen", edgecolor="black", figsize=(8, 8))
plt.title("Brazil")
plt.show()

print(world['NAME'].unique())
# verificando como o nome do brasil esta escrito para o prompt funcionar

# 500 km = 500000 m

brazil_buffer = brazil.buffer(500000)

fig, ax = plt.subplots(figsize=(6, 6))
brazil.plot(ax=ax, color="lightgreen", edgecolor="black")
brazil_buffer.plot(ax=ax, color="red", alpha=0.3)
plt.title("Brazil + 500 km buffer")
plt.show()
# adicionei um buffer de 500 km em volta do brasil na coloração vermelha mais como o alfa ta em 0.3 faz o vermelho ficar mais fosco deixando a gente ver o verde do contorno do brasil.

# calcular a área do brasil
brazil_area_km2 = brazil.area / 1e6
brazil_area_km2

# vamos ver quais países intersectam o buffer do brasil
intersecting = world[world.intersects(brazil_buffer.unary_union)]

fig, ax = plt.subplots(figsize=(6, 6))
intersecting.plot(ax=ax, color="orange", edgecolor="black")
brazil.plot(ax=ax, color="green")
plt.title("Countries intersecting Brazil buffer")
plt.show()

intersecting["NAME"]
# Países vizinhos