# -*- coding: utf-8 -*-
"""Crs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-te6TXbELEx2TCWqSaZkw_zqOeqPkTc0
"""

!wget https://naturalearth.s3.amazonaws.com/110m_cultural/ne_110m_admin_0_countries.zip

!unzip ne_110m_admin_0_countries.zip

!ls

import geopandas as gpd
world = gpd.read_file('ne_110m_admin_0_countries.shp')

world.crs

world.area.head()

world_m = world.to_crs(epsg=3857)

world_m.crs

world_m.area.head()

south_america = world_m[world_m["CONTINENT"] == "South America"]

import matplotlib.pyplot as plt
south_america.plot(figsize=(8, 8), color="lightblue", edgecolor="black")
plt.title("South America - projected CRS (meters)")
plt.show()