# -*- coding: utf-8 -*-
"""geotiff.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GznUmBCS9HmbNVIUYrPNVxR5TfTLyAk0
"""

import geopandas as gpd
import rasterio
from shapely.geometry import point

import geopandas as gpd
print(gpd.__version__)

import geopandas as gpd
import pandas as pd
import matplotlib.pyplot as plt

!wget http://naturalearth.s3.amazonaws.com/110m_cultural/ne_110m_admin_0_countries.zip

!unzip ne_110m_admin_0_countries.zip

import geopandas as gpd
world = gpd.read_file('ne_110m_admin_0_countries.shp')

world.head()

import matplotlib.pyplot as plt
world.plot(figsize=(12, 6))
plt.show()

south_america = world[world["CONTINENT"] == "South America"]

south_america.plot(figsize=(8, 8), color="lightgreen", edgecolor="black")