# -*- coding: utf-8 -*-
"""KDE_Moran.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Yai5LU9PpN0MB39571dr7VLxg-vVbNi
"""

# monta o meu drive aqui no colab/máquina virtual
from google.colab import drive
drive.mount('/content/drive')

cd /content/drive/MyDrive//INMET/

# Importamos o pandas para ler o CSV
import pandas as pd

# Leitura do CSV
df = pd.read_csv('sicor-interest-data.csv')

# Quantas linhas temos?
print(f"Total de registros carregados: {len(df)}")

# Ajuste de tipos de dados
#Algumas colunas chegam como texto mas precisamos que sejam números (latitude, longitude, área) ou datas. Vamos converter uma a uma.


df = df.rename(columns={'latitude_centroide':'latitude', 'longitude_centroide':'longitude'})

# Converter latitude e longitude para números
df['longitude'] = pd.to_numeric(df['longitude'], errors='coerce')
df['latitude']  = pd.to_numeric(df['latitude'],  errors='coerce')

# Converter área para número
df['area_gleba_ha'] = pd.to_numeric(df['area_gleba_ha'], errors='coerce')

# Converter ano para número inteiro
df['ano_emissao'] = pd.to_numeric(df['ano_emissao'], errors='coerce')

# Converter colunas de datas
colunas_datas = [
    'dt_inicio_evento', 'dt_fim_evento', 'dt_comunicacao',
    'dt_inicio_plantio', 'dt_fim_plantio',
    'dt_inicio_colheita', 'dt_fim_colheita',
]
for col in colunas_datas:
    df[col] = pd.to_datetime(df[col], errors='coerce')

print("Tipos de dados após conversão:")
print(df[['longitude', 'latitude', 'area_gleba_ha', 'ano_emissao', 'dt_inicio_evento']].dtypes)

# Remoção de registros sem coordenadas & ajuste nas coordenadas

# Contar quantos registros não têm coordenadas
sem_lon = df['longitude'].isna().sum()
sem_lat = df['latitude'].isna().sum()
print(f"Registros sem longitude: {sem_lon}")
print(f"Registros sem latitude:  {sem_lat}")

# Remover esses registros
df = df.dropna(subset=['longitude', 'latitude'])
print(f"\nRegistros restantes após limpeza: {len(df)}")

# aqui fazemos o ajuste nas coordenadas para garantir que são no BR
df['longitude'] = df['longitude'].abs()*-1
df = df.loc[df['latitude'][(df['latitude'] >= -34) & (df['latitude'] <= 6)].index]
df = df.loc[df['longitude'][(df['longitude'] >= -75) & (df['longitude'] <= -33)].index]

# Aqui vamos simplificar nossas coordenadas para não pesar muito nas análises
df[['longitude', 'latitude']] = df[['longitude', 'latitude']].round(2).drop_duplicates()

#Exploração inicial dos dados
#Antes de aplicar qualquer técnica estatística, vale a pena olhar os dados. Vamos responder algumas perguntas básicas:

#Quantos sinistros por fenômeno adverso?
#Quantos por estado?
#Quantos por safra?

# Quantos sinistros por fenômeno adverso?
print("=== Sinistros por fenômeno adverso ===")
contagem_evento = df['nome_evento'].value_counts()
print(contagem_evento)
print()

# Quantos por estado?
print("=== Sinistros por estado ===")
contagem_estado = df['cd_estado'].value_counts()
print(contagem_estado)
print()

# Quantos por ano-safra?
print("=== Sinistros por ano-safra ===")
contagem_ano = df['ano_emissao'].value_counts().sort_index()
print(contagem_ano)

#Gráfico de barras — Sinistros por fenômeno
#Um gráfico simples nos dá uma visão rápida de quais fenômenos causam mais perdas.

import matplotlib.pyplot as plt

# Contagem por fenômeno adverso
contagem_evento = df['nome_evento'].value_counts()

# Gráfico de barras horizontal
fig, ax = plt.subplots(figsize=(10, 4))
contagem_evento.plot(kind='barh', ax=ax, color='steelblue')
ax.set_xlabel('Número de COPs')
ax.set_ylabel('')
ax.set_title('Comunicações de Perda (COPs) por Fenômeno Adverso — Soja')

# Adiciona os números ao lado de cada barra
for i, v in enumerate(contagem_evento.values):
    ax.text(v + 50, i, f'{v:,}', va='center', fontsize=10)

plt.tight_layout()
plt.show()

"""Primeiro mapa: onde estão as COPs?
Agora vamos colocar os pontos no mapa. Cada ponto é uma COP — uma gleba onde o produtor comunicou perda.

Para isso vamos usar o GeoDataFrame do geopandas. Ele funciona como uma tabela normal do pandas, mas com uma coluna especial chamada geometry que guarda a posição geográfica de cada linha (neste caso, pontos).

"""

import geopandas as gpd
from shapely.geometry import Point

# Criar uma lista de pontos a partir de longitude e latitude
# Cada ponto representa a posição da gleba no mapa
geometrias = []
for lon, lat in zip(df['longitude'], df['latitude']):
    ponto = Point(lon, lat)
    geometrias.append(ponto)

# Criar o GeoDataFrame
# EPSG:4674 = SIRGAS 2000, o sistema de coordenadas oficial do Brasil
gdf = gpd.GeoDataFrame(df, geometry=geometrias, crs='EPSG:4674')

print(f"GeoDataFrame criado com {len(gdf)} pontos")
print(f"Sistema de coordenadas: {gdf.crs}")
gdf[['ref_bacen', 'nome_evento', 'longitude', 'latitude', 'geometry']].head()

!pip install cartopy
import cartopy.crs as ccrs
import cartopy.feature as cfeature

# Definimos as cores para cada fenômeno
cores = {
    'Seca':                                '#E74C3C',  # vermelho
    'Chuva excessiva':                     '#3498DB',  # azul
    'Granizo':                             '#9B59B6',  # roxo
    'Geada':                               '#1ABC9C',  # verde-água
    'Vento forte':                         '#F39C12',  # amarelo
    'Variação excessiva de temperatura':   '#E67E22',  # laranja
}

proj = ccrs.PlateCarree() # nossa projeção favorita → WGS84

fig, ax = plt.subplots(figsize=(12, 10), subplot_kw={'projection': proj})

# Plotar cada fenômeno separadamente (assim temos a legenda com as cores certas)
for evento, cor in cores.items():
    # Filtrar apenas as linhas deste fenômeno
    mascara = gdf['nome_evento'] == evento
    quantidade = mascara.sum()

    if quantidade > 0:
        gdf[mascara].plot(
            ax=ax,
            color=cor,
            markersize=2,
            alpha=0.3,
            label=f'{evento} ({quantidade:,})',
        )

ax.add_feature(cfeature.BORDERS, linewidth=0.5, edgecolor='gray')
ax.add_feature(cfeature.STATES, linewidth=0.3, edgecolor='gray', linestyle='--')
ax.add_feature(cfeature.COASTLINE, linewidth=0.5)
ax.add_feature(cfeature.LAND, facecolor='#f0f0f0')
ax.add_feature(cfeature.OCEAN, facecolor='#d4e6f1')

ax.set_xlabel('Longitude')
ax.set_ylabel('Latitude')
ax.set_title('COPs de Soja — Todos os Fenômenos', fontsize=14)
ax.legend(loc='lower right', fontsize=9, markerscale=5)

plt.tight_layout()
plt.show()

"""Estimativa de Densidade de Kernel (KDE)
 O problema: pontos demais, padrão de menos
Quando plotamos milhares de pontos no mapa (como fizemos acima), é difícil enxergar onde realmente estão as concentrações. Os pontos se sobrepõem, e regiões com 10 COPs parecem iguais a regiões com 1.000 COPs.

Precisamos de uma forma de transformar esses pontos discretos em uma superfície contínua de densidade — algo como um "mapa de calor" que mostra onde os eventos se concentram mais.

É exatamente isso que o KDE (Kernel Density Estimation) faz.
"""

# Filtrar apenas COPs por Seca
df_seca = df[df['nome_evento'] == 'Seca'].copy()

print(f"Total de COPs por Seca: {len(df_seca)}")
print(f"Período: {df_seca['ano_emissao'].min():.0f} a {df_seca['ano_emissao'].max():.0f}")
print(f"Longitude: de {df_seca['longitude'].min():.2f} a {df_seca['longitude'].max():.2f}")
print(f"Latitude:  de {df_seca['latitude'].min():.2f} a {df_seca['latitude'].max():.2f}")

import numpy as np

# Extrair coordenadas das COPs de Seca como arrays
longitude_seca = df_seca['longitude'].values
latitude_seca  = df_seca['latitude'].values

print(f"Temos {len(longitude_seca)} pontos para o KDE")
print(f"Tipo do objeto: {type(longitude_seca)}")
print(f"Formato (shape): {longitude_seca.shape}")

# Precisamos definir uma "malha" de pontos sobre a área de estudo. Cada ponto da malha receberá um valor de densidade.

#Pense na malha como um tabuleiro de xadrez colocado sobre o mapa: vamos calcular a densidade em cada "casa" do tabuleiro.

# Limites da área de estudo (com uma margem de 0.5 grau em cada lado)
lon_min = df_seca['longitude'].min() - 0.5
lon_max = df_seca['longitude'].max() + 0.5
lat_min = df_seca['latitude'].min() - 0.5
lat_max = df_seca['latitude'].max() + 0.5

print(f"Limites da área de estudo:")
print(f"  Longitude: {lon_min:.2f} a {lon_max:.2f}")
print(f"  Latitude:  {lat_min:.2f} a {lat_max:.2f}")

# Criar 200 pontos igualmente espaçados em cada direção
# 200 × 200 = 40.000 pontos — suficiente para boa resolução sem travar o Colab
grade_lon = np.linspace(lon_min, lon_max, 200)
grade_lat = np.linspace(lat_min, lat_max, 200)

# meshgrid cria todas as combinações possíveis de lon × lat
grade_lon_2d, grade_lat_2d = np.meshgrid(grade_lon, grade_lat)

print(f"\nGrade criada: {grade_lon_2d.shape[0]} × {grade_lon_2d.shape[1]} = {grade_lon_2d.size:,} pontos")

"""Calcular o KDE
A função gaussian_kde do SciPy faz o cálculo para nós. Ela:

Recebe os pontos observados (nossas COPs)
Ajusta automaticamente o bandwidth (método de Scott)
Estima a densidade em qualquer ponto que pedirmos
"""

from scipy.stats import gaussian_kde


# O gaussian_kde espera os dados no formato 2 × N
# (primeira linha = longitudes, segunda linha = latitudes)
coordenadas_seca = np.vstack([longitude_seca, latitude_seca])

# Remover possíveis NaNs (Not a Number) gerados anteriormente
coordenadas_seca = coordenadas_seca[:, ~np.isnan(coordenadas_seca).any(axis=0)]

print(f"Formato da entrada para o KDE: {coordenadas_seca.shape}")
print(f"  Linha 0 = longitudes ({coordenadas_seca.shape[1]} valores)")
print(f"  Linha 1 = latitudes  ({coordenadas_seca.shape[1]} valores)")

# Criar o estimador KDE
kde = gaussian_kde(coordenadas_seca, bw_method='scott')

print(f"\nKDE criado! Bandwidth estimado (Scott): {kde.factor:.4f}")

# "Achatar" a grade 2D em uma lista de pontos (2 × 40.000)
pontos_grade = np.vstack([grade_lon_2d.ravel(), grade_lat_2d.ravel()])

# Calcular a densidade em cada ponto da grade
densidade = kde(pontos_grade)

# Reorganizar de volta para o formato 2D (200 × 200)
densidade_2d = densidade.reshape(grade_lon_2d.shape)

print(f"Densidade calculada!")
print(f"Formato: {densidade_2d.shape}")
print(f"Valor mínimo: {densidade_2d.min():.6f}")
print(f"Valor máximo: {densidade_2d.max():.6f}")

# Plotar o mapa de calor
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from mpl_toolkits.axes_grid1.inset_locator import inset_axes


states = cfeature.NaturalEarthFeature(
    category='cultural',
    name='admin_1_states_provinces_lines',
    scale='10m',
    facecolor='none'
)

fig, (ax1, ax2) = plt.subplots(
    1, 2, figsize=(12, 9),
    subplot_kw={'projection': ccrs.PlateCarree()}
)

# Extent único para os dois plots
lon_all = np.concatenate([grade_lon_2d.ravel(), np.asarray(longitude_seca)])
lat_all = np.concatenate([grade_lat_2d.ravel(), np.asarray(latitude_seca)])

pad_lon = 0.5
pad_lat = 0.5

extent = [
    np.nanmin(lon_all) - pad_lon,
    np.nanmax(lon_all) + pad_lon,
    np.nanmin(lat_all) - pad_lat,
    np.nanmax(lat_all) + pad_lat,
]

# =========================
# Painel 1: KDE
# =========================

# pegando vmin e vmax dos dados, assumindo vmin 0, e montando o levels
vmin = 0
vmax = 0.075
levels = np.arange(vmin, vmax, 0.005)

contorno = ax1.contourf(
    grade_lon_2d, grade_lat_2d, densidade_2d,
    levels=levels, vmin=vmin, vmax=vmax, cmap='YlOrRd',
    extend='max',
    transform=ccrs.PlateCarree()
)

ax1.add_feature(cfeature.LAND, facecolor='#f0f0f0')
ax1.add_feature(cfeature.OCEAN, facecolor='#d4e6f1')
ax1.add_feature(cfeature.COASTLINE, linewidth=0.5)
ax1.add_feature(cfeature.BORDERS, linewidth=0.5, edgecolor='gray')
ax1.add_feature(states, linewidth=0.3, edgecolor='gray', linestyle='--')
ax1.set_extent(extent, crs=ccrs.PlateCarree())

ax1.set_xlabel('Longitude')
ax1.set_ylabel('Latitude')
ax1.set_title('KDE — COPs por seca — soja', fontsize=13)

# Colorbar dentro do ax1
cax = inset_axes(
    ax1,
    width="3.5%",
    height="25%",
    loc="lower right",
    borderpad=6
)

cbar = plt.colorbar(contorno, cax=cax)
cbar.set_label('Densidade estimada (KDE)', fontsize=9)
cbar.ax.tick_params(labelsize=8)

# =========================
# Painel 2: Pontos originais
# =========================
ax2.scatter(
    longitude_seca, latitude_seca,
    s=0.5, alpha=0.1, color='black',
    label=f'COPs seca ({len(longitude_seca):,})',
    transform=ccrs.PlateCarree()
)

ax2.add_feature(cfeature.LAND, facecolor='#f0f0f0')
ax2.add_feature(cfeature.OCEAN, facecolor='#d4e6f1')
ax2.add_feature(cfeature.COASTLINE, linewidth=0.5)
ax2.add_feature(cfeature.BORDERS, linewidth=0.5, edgecolor='gray')
ax2.add_feature(states, linewidth=0.3, edgecolor='gray', linestyle='--')
ax2.set_extent(extent, crs=ccrs.PlateCarree())

ax2.set_xlabel('Longitude')
ax2.set_ylabel('Latitude')
ax2.set_title('Pontos de COPs por seca — soja', fontsize=13)
ax2.legend(loc='lower left', markerscale=20)

plt.tight_layout()

# Salvar a imagem
plt.savefig('KDE_COPs_Seca_Soja.png', dpi=300, bbox_inches='tight')

plt.show()

"""Efeito do bandwidth — Vendo na prática
O bandwidth é o parâmetro mais importante do KDE. Ele controla o nível de suavização:

Bandwidth pequeno: revela detalhes locais, mas pode criar "ruído" (picos falsos)
Bandwidth grande: suaviza demais e pode esconder padrões reais
Vamos comparar três valores de bandwidth para os mesmos dados.
"""

from scipy.stats import gaussian_kde
import matplotlib.pyplot as plt
import numpy as np
import cartopy.crs as ccrs
import cartopy.feature as cfeature

# Fazer um recorte aproximado para a Região Sul do Brasil
# (Latitudes entre -34 e -22, Longitudes entre -58 e -48)
mask_sul = (coordenadas_seca[0] >= -58.5) & (coordenadas_seca[0] <= -47.5) & \
           (coordenadas_seca[1] >= -34.0) & (coordenadas_seca[1] <= -22.0)

coords_sul = coordenadas_seca[:, mask_sul]

# Criar uma nova grade menor, focada apenas na Região Sul
lon_min, lon_max = coords_sul[0].min() - 0.5, coords_sul[0].max() + 0.5
lat_min, lat_max = coords_sul[1].min() - 0.5, coords_sul[1].max() + 0.5

g_lon = np.linspace(lon_min, lon_max, 150)
g_lat = np.linspace(lat_min, lat_max, 150)
g_lon_2d, g_lat_2d = np.meshgrid(g_lon, g_lat)
pontos_g = np.vstack([g_lon_2d.ravel(), g_lat_2d.ravel()])

# Três bandwidths para comparar
bandwidths = [0.05, 'scott', 0.3]
titulos = [
    'Bandwidth = 0.05\n(muito detalhado)',
    'Bandwidth = Scott\n(automático)',
    'Bandwidth = 0.3\n(muito suavizado)',
]

# Passar a projeção para todos os subplots na hora de criá-los
fig, eixos = plt.subplots(1, 3, figsize=(18, 6), subplot_kw={'projection': ccrs.PlateCarree()})

for i in range(3):
    bw = bandwidths[i]
    titulo = titulos[i]

    # Criar KDE com este bandwidth usando apenas os pontos do Sul
    kde_i = gaussian_kde(coords_sul, bw_method=bw)

    # Calcular densidade na grade reduzida
    dens_i = kde_i(pontos_g).reshape(g_lon_2d.shape)

    # Plotar no eixo correspondente (ax)
    ax = eixos[i]
    ax.contourf(g_lon_2d, g_lat_2d, dens_i, levels=30, cmap='YlOrRd')
    ax.set_title(titulo, fontsize=11)
    ax.set_xlabel('Longitude')
    if i == 0:
        ax.set_ylabel('Latitude')

    ax.set_xlim(lon_min, lon_max)
    ax.set_ylim(lat_min, lat_max)

    ax.add_feature(cfeature.LAND, facecolor='#f0f0f0')
    ax.add_feature(cfeature.OCEAN, facecolor='#d4e6f1')
    ax.add_feature(cfeature.COASTLINE, linewidth=0.5)
    ax.add_feature(cfeature.BORDERS, linewidth=0.5, edgecolor='gray')
    ax.add_feature(states, linewidth=0.3, edgecolor='gray', linestyle='--')

fig.suptitle('Efeito do Bandwidth no KDE — COPs por Seca (Recorte Região Sul)', fontsize=14, fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()

# Comparando fenômenos: Seca vs Chuva excessiva

from scipy.stats import gaussian_kde

import cartopy.feature as cfeature

states = cfeature.NaturalEarthFeature(
    category='cultural',
    name='admin_1_states_provinces_lines',
    scale='10m',
    facecolor='none'
)

# --- Dados de Seca ---
df_seca = df[df['nome_evento'] == 'Seca']
coords_seca = np.vstack([df_seca['longitude'].values, df_seca['latitude'].values])
# Remover possíveis NaNs
coords_seca = coords_seca[:, ~np.isnan(coords_seca).any(axis=0)]

# Máscara Sul para Seca
mask_sul_seca = (coords_seca[0] >= -58.5) & (coords_seca[0] <= -47.5) & \
                (coords_seca[1] >= -34.0) & (coords_seca[1] <= -22.0)
coords_seca_sul = coords_seca[:, mask_sul_seca]

kde_seca = gaussian_kde(coords_seca_sul, bw_method='scott')

# --- Dados de Chuva excessiva ---
df_chuva = df[df['nome_evento'] == 'Chuva excessiva']
coords_chuva = np.vstack([df_chuva['longitude'].values, df_chuva['latitude'].values])
# Remover possíveis NaNs
coords_chuva = coords_chuva[:, ~np.isnan(coords_chuva).any(axis=0)]

# Máscara Sul para Chuva excessiva
mask_sul_chuva = (coords_chuva[0] >= -58.5) & (coords_chuva[0] <= -47.5) & \
                 (coords_chuva[1] >= -34.0) & (coords_chuva[1] <= -22.0)
coords_chuva_sul = coords_chuva[:, mask_sul_chuva]

kde_chuva = gaussian_kde(coords_chuva_sul, bw_method='scott')

# --- Criar nova grade focada na Região Sul ---
lon_min, lon_max = -58.5, -47.5
lat_min, lat_max = -34.0, -22.0

g_lon = np.linspace(lon_min, lon_max, 150)
g_lat = np.linspace(lat_min, lat_max, 150)
g_lon_2d, g_lat_2d = np.meshgrid(g_lon, g_lat)
pontos_g = np.vstack([g_lon_2d.ravel(), g_lat_2d.ravel()])

# Calcular densidades na nova grade
dens_seca  = kde_seca(pontos_g).reshape(g_lon_2d.shape)
dens_chuva = kde_chuva(pontos_g).reshape(g_lon_2d.shape)

# --- Plotar lado a lado ---
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 7), subplot_kw={'projection': ccrs.PlateCarree()})

# Seca
cf1 = ax1.contourf(g_lon_2d, g_lat_2d, dens_seca, levels=30, cmap='YlOrRd')
plt.colorbar(cf1, ax=ax1, shrink=0.7, label='Densidade')
ax1.set_title(f'Seca ({coords_seca_sul.shape[1]:,} COPs no Sul)', fontsize=12)
ax1.set_xlabel('Longitude')
ax1.set_ylabel('Latitude')
ax1.set_xlim(lon_min, lon_max)
ax1.set_ylim(lat_min, lat_max)
ax1.add_feature(cfeature.LAND, facecolor='#f0f0f0')
ax1.add_feature(cfeature.OCEAN, facecolor='#d4e6f1')
ax1.add_feature(cfeature.COASTLINE, linewidth=0.5)
ax1.add_feature(cfeature.BORDERS, linewidth=0.5, edgecolor='gray')
ax1.add_feature(states, linewidth=0.3, edgecolor='gray', linestyle='--')

# Chuva excessiva
cf2 = ax2.contourf(g_lon_2d, g_lat_2d, dens_chuva, levels=30, cmap='YlGnBu')
plt.colorbar(cf2, ax=ax2, shrink=0.7, label='Densidade')
ax2.set_title(f'Chuva excessiva ({coords_chuva_sul.shape[1]:,} COPs no Sul)', fontsize=12)
ax2.set_xlabel('Longitude')
ax2.set_xlim(lon_min, lon_max)
ax2.set_ylim(lat_min, lat_max)
ax2.add_feature(cfeature.LAND, facecolor='#f0f0f0')
ax2.add_feature(cfeature.OCEAN, facecolor='#d4e6f1')
ax2.add_feature(cfeature.COASTLINE, linewidth=0.5)
ax2.add_feature(cfeature.BORDERS, linewidth=0.5, edgecolor='gray')
ax2.add_feature(states, linewidth=0.3, edgecolor='gray', linestyle='--')

fig.suptitle('Comparação de KDE: Seca vs Chuva Excessiva — Soja (Recorte Região Sul)', fontsize=14, fontweight='bold')
# Salvar a imagem
plt.savefig('seca_vs_chuva_COPs_Soja.png', dpi=300, bbox_inches='tight')
plt.tight_layout()
plt.show()

"""Preparando os Dados para o I de Moran
Por que mudar de pontos para áreas?
O KDE trabalha com pontos (as coordenadas individuais de cada COP). Já o I de Moran trabalha com valores associados a áreas — no nosso caso, municípios.

A pergunta muda:

"Municípios com muitas COPs estão próximos de outros municípios com muitas COPs?"

Para isso, precisamos:

Agregar as COPs por município (contar quantas COPs cada município tem)
Juntar essa contagem ao shapefile de municípios (que tem os polígonos)
Construir a matriz de pesos espaciais (quem é vizinho de quem)
"""

# Contar o número de COPs em cada município
cops_por_municipio = (
    df
    .groupby('cd_ibge_municipio')  # Agrupar pelo código do município
    .size()                        # Contar quantas linhas em cada grupo
    .reset_index(name='total_cops')  # Transformar de volta em tabela
)

# O código do município precisa ser texto (string) para o join com shapefile
cops_por_municipio['cd_ibge_municipio'] = cops_por_municipio['cd_ibge_municipio'].astype(str)

print(f"Municípios com pelo menos 1 COP: {len(cops_por_municipio)}")
print()
print("Top 10 municípios com mais COPs:")
print(cops_por_municipio.sort_values('total_cops', ascending=False).head(10).to_string(index=False))

# Contagem por município E por fenômeno
cops_mun_evento = (
    df
    .groupby(['cd_ibge_municipio', 'nome_evento'])
    .size()
    .reset_index(name='total_cops')
)

# Pivotar: transformar em uma tabela com uma coluna para cada fenômeno
tabela_pivot = cops_mun_evento.pivot_table(
    index='cd_ibge_municipio',
    columns='nome_evento',
    values='total_cops',
    fill_value=0,     # Municípios sem aquele fenômeno recebem 0
).reset_index()

# Converter código para string
tabela_pivot['cd_ibge_municipio'] = tabela_pivot['cd_ibge_municipio'].astype(str)

print(f"Tabela com {len(tabela_pivot)} municípios")
print(f"Colunas: {list(tabela_pivot.columns)}")
tabela_pivot.head()

# Leitura do shapefile de municípios

gdf_mun = gpd.read_file('BR_Municipios_2024.zip')

# Filtrar apenas RS e PR
# gdf_mun = gdf_mun[gdf_mun['SIGLA_UF'].isin(['RS', 'PR'])].copy()

# Garantir que estamos em SIRGAS 2000
gdf_mun = gdf_mun.to_crs('EPSG:4674')

# Padronizar o código do município para string
gdf_mun['CD_MUN'] = gdf_mun['CD_MUN'].astype(str)

print(f"Municípios no shapefile: {len(gdf_mun)}")
gdf_mun[['CD_MUN', 'NM_MUN', 'SIGLA_UF']].head()

# Juntar contagem total de COPs ao shapefile
gdf_analise = gdf_mun.merge(
    cops_por_municipio,
    left_on='CD_MUN',
    right_on='cd_ibge_municipio',
    how='left',   # Manter TODOS os municípios, mesmo sem COP
)

# Municípios sem COP ficam com NaN — vamos preencher com 0
gdf_analise['total_cops'] = gdf_analise['total_cops'].fillna(0).astype(int)

print(f"Total de municípios: {len(gdf_analise)}")
print(f"  Com COPs: {(gdf_analise['total_cops'] > 0).sum()}")
print(f"  Sem COPs: {(gdf_analise['total_cops'] == 0).sum()}")

# Juntar também a tabela pivotada (COPs por fenômeno)
gdf_analise = gdf_analise.merge(
    tabela_pivot,
    on='cd_ibge_municipio',
    how='left',
)

# Preencher NaN com 0 nas colunas de fenômenos
colunas_fenomeno = [c for c in tabela_pivot.columns if c != 'cd_ibge_municipio']
for col in colunas_fenomeno:
    if col in gdf_analise.columns:
        gdf_analise[col] = gdf_analise[col].fillna(0).astype(int)

print("Colunas disponíveis:")
print([c for c in gdf_analise.columns if c not in ['geometry', 'cd_ibge_municipio']])

# Plotando mapa por municipio
fig, ax = plt.subplots(figsize=(14, 9), subplot_kw={'projection': ccrs.PlateCarree()})

gdf_analise[gdf_analise['total_cops'] > 0 ].plot(
    column='total_cops',       # Coluna que define a cor
    cmap='Spectral_r',             # Esquema de cores
    vmin=1,
    vmax=5000,
    legend=True,
    legend_kwds={
        'label': 'Nº de COPs por município',
        'shrink': 0.7,
        'pad':0.01
    },
    ax=ax,
)

ax.set_xlabel('Longitude')
ax.set_ylabel('Latitude')

ax.add_feature(cfeature.LAND, facecolor='#f0f0f0')
ax.add_feature(cfeature.OCEAN, facecolor='#d4e6f1')
ax.add_feature(cfeature.COASTLINE, linewidth=0.5)
ax.add_feature(cfeature.BORDERS, linewidth=0.5, edgecolor='gray')
ax.add_feature(states, linewidth=0.3, edgecolor='gray', linestyle='--')

ax.set_title('Total de COPs de Soja por Município', fontsize=14)
plt.savefig('municipio_COPs_Soja.png', dpi=300, bbox_inches='tight')
plt.tight_layout()
plt.show()

"""A pergunta central
Olhando o mapa coroplético, parece que municípios com muitas COPs estão próximos de outros municípios com muitas COPs. Mas será que isso é real ou é apenas impressão visual?

O I de Moran Global é um teste estatístico que responde exatamente essa pergunta:

"Os valores que observamos (neste caso, número de COPs) estão organizados espacialmente de forma não aleatória?"

O resultado é um número entre -1 e +1.
"""

# Importar a ferramenta de pesos espaciais do PySAL
from libpysal.weights import Queen

# Construir a matriz de vizinhança Queen
pesos = Queen.from_dataframe(gdf_analise, use_index=False)

print(f"Matriz de pesos criada!")
print(f"  Número de municípios: {pesos.n}")
print(f"  Número médio de vizinhos por município: {pesos.mean_neighbors:.1f}")
print(f"  Mínimo de vizinhos: {pesos.min_neighbors}")
print(f"  Máximo de vizinhos: {pesos.max_neighbors}")

# Vamos ver os vizinhos do município com mais COPs

# Descobrir qual é o município com maior total_cops
idx_mais_cops = gdf_analise['total_cops'].idxmax()
nome_mun = gdf_analise.loc[idx_mais_cops, 'NM_MUN']
uf_mun   = gdf_analise.loc[idx_mais_cops, 'SIGLA_UF']
n_viz    = len(pesos.neighbors[idx_mais_cops])
cops_mun = gdf_analise.loc[idx_mais_cops, 'total_cops']

print(f"Município com mais COPs: {nome_mun}/{uf_mun}")
print(f"  Total de COPs neste município: {cops_mun}")
print(f"  Número de vizinhos: {n_viz}")
print()

# Mostrar os nomes e COPs dos vizinhos
print(f"Vizinhos de {nome_mun}:")
for idx_v in pesos.neighbors[idx_mais_cops]:
    nome_v = gdf_analise.loc[idx_v, 'NM_MUN']
    cops_v = gdf_analise.loc[idx_v, 'total_cops']
    print(f"  → {nome_v}: {cops_v} COPs")

from matplotlib.patches import Patch

fig, ax = plt.subplots(figsize=(12, 9))

# Todos os municípios em cinza claro (fundo)
gdf_analise.plot(ax=ax, color='#f0f0f0', edgecolor='gray', linewidth=0.3)

# Vizinhos em azul
vizinhos_idx = pesos.neighbors[idx_mais_cops]
gdf_analise.iloc[vizinhos_idx].plot(ax=ax, color='#3498DB', edgecolor='gray', linewidth=0.5)

# Município central em vermelho
mun_central = gdf_analise.iloc[[idx_mais_cops]]
mun_central.plot(ax=ax, color='#E74C3C', edgecolor='black', linewidth=1.5)

# Calcular o centroide para definir o zoom (extent de ±1°)
centroide = mun_central.geometry.centroid.iloc[0]
ax.set_xlim(centroide.x - 1, centroide.x + 1)
ax.set_ylim(centroide.y - 1, centroide.y + 1)

ax.legend(
    handles=[
        Patch(facecolor='#E74C3C', edgecolor='black', label=f'{nome_mun} ({n_viz} vizinhos)'),
        Patch(facecolor='#3498DB', edgecolor='gray', label='Vizinhos (critério Queen)'),
        Patch(facecolor='#f0f0f0', edgecolor='gray', label='Demais municípios'),
    ],
    loc='lower left',
    fontsize=10,
)
ax.set_title(f'Vizinhança Queen — {nome_mun}/{uf_mun}', fontsize=13)
ax.set_xlabel('Longitude')
ax.set_ylabel('Latitude')

plt.tight_layout()
plt.show()

"""Com a matriz de pesos pronta, calcular o I de Moran é simples: basta passar os valores (total de COPs) e os pesos (vizinhança).

O PySAL cuida de toda a matemática, incluindo o teste de significância: ele embaralha os valores entre os municípios 999 vezes (permutações de Monte Carlo) e verifica se o I observado é diferente do que surgiria por acaso.
"""

# Aqui vamos usar a vizinhança do tipo Queen.
# Ela considera como vizinhos os municípios que encostam por lado ou vértice.
w = Queen.from_dataframe(gdf_analise)

# Island é um município que ficou sem vizinhos na matriz de pesos.
print("Islands:", w.islands)

# Remover os islands antes de calcular o Moran
gdf_sem_islands = gdf_analise.drop(index=w.islands).copy()
gdf_sem_islands = gdf_sem_islands.reset_index(drop=True)

# Agora recriamos a matriz de pesos
w = Queen.from_dataframe(gdf_sem_islands)
w.transform = "r"

gdf_sem_islands

from esda.moran import Moran

# Valores: total de COPs por município
valores = gdf_sem_islands['total_cops'].values

# Calcular o I de Moran Global com 999 permutações de Monte Carlo
moran_global = Moran(valores, w, permutations=999)

print("=" * 55)
print("  RESULTADO — I de Moran Global (total de COPs)")
print("=" * 55)
print(f"  I de Moran observado:        {moran_global.I:.4f}")
print(f"  Valor esperado (aleatório):  {moran_global.EI:.4f}")
print(f"  p-valor (Monte Carlo):       {moran_global.p_sim:.4f}")
print(f"  z-score:                     {moran_global.z_sim:.4f}")
print("=" * 55)

# Interpretação do p-valor
if moran_global.p_sim < 0.01:
    sig = "altamente significativo (p < 0.01)"
elif moran_global.p_sim < 0.05:
    sig = "significativo (p < 0.05)"
else:
    sig = "NÃO significativo (p ≥ 0.05)"

# Interpretação da direção
if moran_global.I > 0:
    direcao = "POSITIVA — municípios vizinhos tendem a ter valores semelhantes"
elif moran_global.I < 0:
    direcao = "NEGATIVA — municípios vizinhos tendem a ter valores opostos"
else:
    direcao = "NULA — sem padrão detectável"

print(f"Autocorrelação espacial: {direcao}")
print(f"Significância estatística: {sig}")
print()
print("Em termos práticos:")
print(f"  O I = {moran_global.I:.4f} indica que municípios com muitas COPs")
print(f"  estão próximos de outros municípios com muitas COPs.")
print(f"  O p-valor = {moran_global.p_sim:.4f} indica que este padrão")
if moran_global.p_sim < 0.05:
    print(f"  é estatisticamente significativo — NÃO é fruto do acaso.")
else:
    print(f"  pode ser explicado pelo acaso.")

sim = moran_global.sim
I_obs = moran_global.I
EI = moran_global.EI

x = np.linspace(sim.min(), sim.max(), 500)
kde = gaussian_kde(sim)
y_kde = kde(x)

fig, ax = plt.subplots(figsize=(10, 6))

# Histograma
ax.hist(
    sim,
    bins=30,
    density=True,
    color="lightgray",
    edgecolor="gray",
    label="Permutações"
)

# KDE
ax.plot(x, y_kde, linewidth=2, label="KDE")

# Linha do valor esperado
ax.axvline(
    EI,
    color="black",
    linestyle="--",
    label=f"Valor esperado = {EI:.4f}"
)

ax.set_title(
    f"Distribuição nula de I de Moran\n"
    f"I observado = {I_obs:.4f} | p = {moran_global.p_sim:.4f}"
)
ax.set_xlabel("I de Moran permutado")
ax.set_ylabel("Densidade")
ax.legend()
ax.grid(alpha=0.2)

# Inset
ax_inset = inset_axes(ax, width="38%", height="22%", loc="upper right")

ax_inset.axvspan(sim.min(), sim.max(), color="lightgray", alpha=0.8)
ax_inset.axvline(EI, color="black", linestyle="--")
ax_inset.axvline(I_obs, color="red", linewidth=2)

ax_inset.set_xlim(min(sim.min(), I_obs) - 0.02, max(sim.max(), I_obs) + 0.02)
ax_inset.set_yticks([])
ax_inset.set_xlabel("Escala completa", fontsize=9)
ax_inset.tick_params(axis="x", labelsize=8)

plt.show()

from splot.esda import moran_scatterplot
import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(8, 8))

# O splot gera o diagrama de espalhamento completo
moran_scatterplot(moran_global, ax=ax, aspect_equal=True)

ax.set_title(
    f'Diagrama de Espalhamento de Moran\n'
    f'I = {moran_global.I:.4f} (p = {moran_global.p_sim:.4f})',
    fontsize=13
)
ax.set_xlabel('COPs por município (padronizado)', fontsize=11)
ax.set_ylabel('Média dos vizinhos (padronizado)', fontsize=11)

plt.savefig('i_moran.png', dpi=300, bbox_inches='tight')
plt.tight_layout()
plt.show()

# Lista de fenômenos para testar
fenomenos = ['Seca', 'Chuva excessiva', 'Granizo', 'Geada']

print("=" * 65)
print(f"  {'Fenômeno':<25} {'I Moran':>10} {'p-valor':>10} {'Significativo?':>15}")
print("=" * 65)

for fenomeno in fenomenos:
    if fenomeno in gdf_analise.columns:
        valores_f = gdf_analise[fenomeno].values
        moran_f = Moran(valores_f, pesos, permutations=999)

        if moran_f.p_sim < 0.01:
            sig = "Sim ***"
        elif moran_f.p_sim < 0.05:
            sig = "Sim *"
        else:
            sig = "Não"

        print(f"  {fenomeno:<25} {moran_f.I:>10.4f} {moran_f.p_sim:>10.4f} {sig:>15}")

print("=" * 65)
print()
print("Legenda: *** = p < 0.01 | * = p < 0.05")