# -*- coding: utf-8 -*-
"""map_quantiles.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nBzIGf_Xpq3M26XZUwj35aqfn6Rhi4ZE
"""

!wget https://naturalearth.s3.amazonaws.com/110m_cultural/ne_110m_admin_0_countries.zip

!unzip ne_110m_admin_0_countries.zip

import geopandas as gpd
import matplotlib.pyplot as plt

world = gpd.read_file('ne_110m_admin_0_countries.shp')
world = world.to_crs(epsg=3857)

world.columns

world.plot(
    column="SOVEREIGNT",
    cmap="OrRd",
    legend=True,
    figsize=(14, 8)
)
plt.title("World countries (thematic map)")
plt.show()

!wget https://naturalearth.s3.amazonaws.com/50m_cultural/ne_50m_admin_0_countries_simplified.zip

"""**Reasoning**:
The previous attempt to download the file resulted in a 404 error, indicating the provided URL is incorrect. I will try a different URL for the 'ne_50m_admin_0_countries' dataset, as the 'simplified' version might not be available or named differently.


"""

import requests
url = 'https://naturalearth.s3.amazonaws.com/50m_cultural/ne_50m_admin_0_countries.zip'
response = requests.get(url)

if response.status_code == 200:
    with open('ne_50m_admin_0_countries.zip', 'wb') as f:
        f.write(response.content)
    print('File downloaded successfully!')
else:
    print(f'Failed to download file. Status code: {response.status_code}')

import zipfile

with zipfile.ZipFile('ne_50m_admin_0_countries.zip', 'r') as zip_ref:
    zip_ref.extractall('.')
print('Files extracted successfully!')

ne_50m_world = gpd.read_file('ne_50m_admin_0_countries.shp')
ne_50m_world.head()

ne_50m_world.columns

if 'POP_EST' in ne_50m_world.columns:
    print(ne_50m_world['POP_EST'].describe())
else:
    print("Column 'POP_EST' not found. Please check other column names for population data.")

world.plot(
    column="POP_EST",
    cmap="OrRd",
    legend=True,
    figsize=(20, 8)
)

plt.title("World population (thematic map)")
plt.show()

south_america = world[world["CONTINENT"] == "South America"]

south_america.plot(
    column="POP_EST",
    cmap="OrRd",
    legend=True,
    edgecolor="black",
    figsize=(8, 8)
)
plt.title("South America population (thematic map)")
plt.show()

south_america.plot(
    columns="POP_EST",
    cmap="YlGn",
    scheme="quantiles",
    K=5,
    legend=True,
    edgecolor="black",
    figsize(8, 8)
)
plt.title("South America population (quantiles)")
plt.show()

"""**Reasoning**:
To fix the `SyntaxError`, I will modify the `figsize` argument in the `plot()` function call by changing `figsize(8, 8)` to `figsize=(8, 8)`.

**Reasoning**:
The previous error message indicates that the `plot` function in GeoPandas expects the keyword argument `column` for specifying the data column to plot, not `columns`. I need to change `columns` to `column` to resolve this `AttributeError`.
"""

south_america.plot(
    column="POP_EST",
    cmap="YlGn",
    scheme="quantiles",
    k=5,
    legend=True,
    edgecolor="black",
    figsize=(8, 8)
)
plt.title("South America population (quantiles)")
plt.show()

"""## Gerar o Mapa de População da América do Sul por Quantis

### Subtask:
Confirm that the South America population map by quantiles has been successfully generated and displayed.

## Summary:

### Data Analysis Key Findings
*   The initial syntax error `figsize(8, 8)` was successfully corrected to `figsize=(8, 8)`.
*   After correcting the `figsize` syntax, an `AttributeError` was encountered because `plot()` did not accept `columns` as a keyword argument; this was resolved by changing `columns="POP_EST"` to `column="POP_EST"`.
*   Following the correction of the column argument, another `AttributeError` occurred, indicating that `K` was not a valid keyword for the number of classes; this was rectified by changing `K=5` to `k=5`.
*   All identified errors were resolved, and the thematic map of South America's population by quantiles was successfully generated and displayed.

### Insights or Next Steps
*   Ensure careful review of function documentation for precise keyword arguments to prevent syntax and `AttributeError`s in plotting functions.
*   Implement a robust error-handling or validation step during development to catch common plotting library keyword discrepancies early.
"""