# -*- coding: utf-8 -*-
"""NDVI_SENTINEL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gqhQqBDUETtYZ7jQYT5zzBNLIPydOJpt
"""

!pip install rasterio numpy matplotlib

!pip install sentinelhub

# Buscando imagens do satelite sentinel 2

from sentinelhub import (
    SHConfig,
    SentinelHubRequest,
    DataCollection,
    bbox_to_dimensions,
    BBox,
    CRS,
    MimeType
)

config = SHConfig()

config.sh_client_id = "481d7993-0fc2-40ee-9322-4dc9db0aec48"
config.sh_client_secret = "QHI5Tv3vIoMAkxk1C8YR1899u3mIlZ3L"

bbox = BBox(bbox=[-55.0, -12.0, -54.9, -11.9], crs=CRS.WGS84)
resolution = 10
size = bbox_to_dimensions(bbox, resolution=resolution)

# Request o NDVI
evalscript = """
//VERSION=3
function setup() {
  return {
    input: ["B04", "B08"],
    output: { bands: 1 }
  };
}

function evaluatePixel(sample) {
  return [(sample.B08 - sample.B04) / (sample.B08 + sample.B04)];
}
"""

request = SentinelHubRequest(
    evalscript=evalscript,
    input_data=[
        SentinelHubRequest.input_data(
            data_collection=DataCollection.SENTINEL2_L2A,
            time_interval=("2023-06-01", "2023-06-30"),
            mosaicking_order="leastCC"
        )
    ],
    responses=[SentinelHubRequest.output_response("default", MimeType.TIFF)],
    bbox=bbox,
    size=size,
    config=config,
)

ndvi = request.get_data()[0]

# O sentinel retorna as vezes o NDVI Escalado então usei esse prompt para obter o real.

ndvi_real=ndvi.astype("float32") / 255.0

# Visualizando
import matplotlib.pyplot as plt

plt.imshow(ndvi_real.squeeze(), cmap="RdYlGn", vmin=-1, vmax=1)
plt.colorbar(label="NDVI")
plt.title("NDVI - Sentinel-2")
plt.axis("off")
plt.show()

# Valores do NDVI

import numpy as np
np.nanmin(ndvi_real), np.nanmax(ndvi_real), np.nanmean(ndvi_real)

