# -*- coding: utf-8 -*-
"""pygis_mini_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17CaDNhA_ze5_WSq9Hklrxot9Y5uOVevE
"""

!pip install geopandas shapely matplotlib

!
!wget http://naturalearth.s3.amazonaws.com/110m_cultural/ne_110m_admin_0_countries.zip
!unzip ne_110m_admin_0_countries.zip.1

import geopandas as gpd

# Lendo o shapefile
world = gpd.read_file("ne_110m_admin_0_countries.shp")

# Coordenadas em crs
display(world.crs)

world = world.to_crs(epsg=3857)

import matplotlib.pyplot as plt

# Funções de análises
def analyze_continent(shapefile, continent_name):
  gdf = gpd.read_file(shapefile).to_crs(epsg=3857)

  continent = gdf[gdf['CONTINENT'] == continent_name].copy()
  continent["area_km2"] = continent.area / 1e6

  total_area = continent["area_km2"].sum()
  print(f"Total area of {continent_name}: {total_area:.2f} km2")

  continent.plot(figsize=(8, 8), edgecolor="black")
  plt.title(continent_name)
  plt.show()
  return continent

# Executando as análises

south_america = analyze_continent("ne_110m_admin_0_countries.shp", "South America")

north_america = analyze_continent("ne_110m_admin_0_countries.shp", "North America")

# Mapa tematico com relação a quantidade em área
south_america.plot(
    column="area_km2",
    cmap="YlOrRd",
    legend=True,
    figsize=(8, 8),
    edgecolor="black"
)
plt.title("South America - area by country (km2)")
plt.show()

# Agora com america do norte
north_america.plot(
    column="area_km2",
    cmap="YlOrRd",
    legend=True,
    figsize=(8, 8),
    edgecolor="black"
)

plt.title("North America - area by country (km2)")
plt.show()