# -*- coding: utf-8 -*-
"""Raster.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wwf7jclT_hi8Waozm75OrdVmiS0pSoQ2
"""

!pip install rasterio numpy matplotlib

# Agora que ja instalei as bibliotecas vou importar.

import rasterio
from rasterio.plot import show
import numpy as np
import matplotlib.pyplot as plt

!wget http://github.com/mapbox/rasterio/raw/main/tests/data/RGB.byte.tif

dem = rasterio.open("RGB.byte.tif")
# Modelos de DEM testes do github

dem.profile
# Informações como em qual UTM está, qual EPSG e outras informações desse DEM.

fig, ax = plt.subplots(1, 1, figsize=(10, 10))
show(dem, cmap="terrain", ax=ax)
ax.set_title("Digital Elevation Model")
plt.show()
# Visualização do DEM.

# Vamos ver valores como matriz
elevation = dem.read(1)

np.min(elevation), np.max(elevation), np.mean(elevation)

# Calcular a Declividade
x, y = np.gradient(elevation)
slope = np.sqrt(x**2 + y**2)

# Visualizar
plt.imshow(slope, cmap="inferno")
plt.colorbar(label="Slope")
plt.title("Slope (relative)")
plt.show()

# Outra visualização
plt.figure(figsize=(8, 6))
plt.imshow(slope, cmap="terrain")
plt.colorbar (label="Slope")
plt.title("Slope derived from DEM")
plt.axis("off")
plt.show()