# -*- coding: utf-8 -*-
"""Raster_DEM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xsB3GFn4R7y9YnQq1oED1MpOV4IvrNI6
"""

!pip install rasterio matplotlib numpy

# Importa bibliotecas
import rasterio
import numpy as np
import matplotlib.pyplot as plt

# Obtendo DEM de exemplo
!wget http://github.com/mapbox/rasterio/raw/main/tests/data/RGB.byte.tif

dem = rasterio.open("RGB.byte.tif")

# Inspecionando as propriedades do raster coisas como: número de bandas,colunas,linhas,sistema de referêrencia,georreferenciamento e valor nodata

print(f"Count: {dem.count}")
print(f"Width: {dem.width}")
print(f"Height: {dem.height}")
print(f"CRS: {dem.crs}")
print(f"Transform: {dem.transform}")
print(f"NoData Value: {dem.nodata}")

array = dem.read(1)
array

# Estatísticas básicas

array.min(), array.max(), array.mean()

# Visualização correta

plt.figure(figsize=(6, 6))
plt.imshow(array, cmap="terrain")
plt.title("DEM visualization")
plt.show()