# -*- coding: utf-8 -*-
"""Slope_Hillshade.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Glx3LcsEAKM6rucvMS5BD2upvoG9gJX-
"""

!pip install rasterio numpy matplotlib

# Importando as bibliotecas
import rasterio
import numpy as np
import matplotlib.pyplot as plt

!wget https://github.com/mapbox/rasterio/raw/main/tests/data/RGB.byte.tif
dem = rasterio.open("RGB.byte.tif")
array = dem.read(1)

# Calcular o gradiente
gy, gx = np.gradient(array)
display(gx)
display(gy)

# Slope em graus
slope = np.sqrt(gx**2 + gy**2)
slope_deg = np.degrees(np.arctan(slope))
display(slope)
display(slope_deg)

# Visualização
plt.figure(figsize=(6, 6))
plt.imshow(slope_deg, cmap="inferno")
plt.colorbar(label="Slpe (degrees)")
plt.title("Slope derived from DEM")
plt.show()

# Calcular hillshade
azimuth = 315
altitude = 45

az_rad = np.radians(azimuth)
alt_rad = np.radians(altitude)

x, y = gx, gy
slope_rad = np.arctan(np.sqrt(x**2 + y**2))
aspect_rad = np.arctan2(-x, y)

hillshade = (
    np.sin(alt_rad) * np.sin(slope_rad)
    + np.cos(alt_rad) * np.cos(slope_rad) * np.cos(az_rad - aspect_rad)
)
hillshade = np.clip(hillshade, 0, 1)

# Visualizar hillshade
plt.figure(figsize=(6, 6))
plt.imshow(hillshade, cmap="gray")
plt.title("Hillshade")
plt.axis("off")
plt.show()