# -*- coding: utf-8 -*-
"""Yuzawa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1De6MMgWk5evQaOT5peq09gxe4GHjD9Wx
"""

pip install ridge_map

from ridge_map import RidgeMap
import matplotlib.pyplot as plt

# Bounding box coordinates for yuzawa
yuzawa_bbox = (138.666989,36.86107,138.797727,36.962967)

rm = RidgeMap(yuzawa_bbox)

# Get Elevation Data
values = rm.get_elevation_data(num_lines=150)

# Preprocess Data
values = rm.preprocess(values=values,
                       lake_flatness=.5,
                       water_ntile=0,
                       vertical_ratio=250)

rm.plot_map(values=values,
            label='Yuzawa',
            label_y=0.1,
            label_x=0.55,
            label_size=40,
            linewidth=1,
            line_color=plt.get_cmap('copper'),
            kind='elevation')
plt.savefig('yuzawa_ridgemap.png', bbox_inches='tight', dpi=300)
plt.show()

